import type { ErrorScope } from "@turnkeyid/utils-ts"
import { modelFactory, BaseError } from "@turnkeyid/utils-ts"

export class ExpressError extends BaseError {
  protected scope: ErrorScope = `PUBLIC`
  public name = `EXPRESS_ERROR`
  public httpStatus = 500
  public message = `unknown error`
  public public_message?: string | undefined = `response error`

  static _factory = modelFactory(ExpressError, {
    allAutoGenerated: true,
  })
}

